### ISSUE TITLE
Multiplayer Support?

### ISSUE THREAD

**Issue by DartPower** [JNechaevsky/yaguar-doom#1]
Can you write the netcode from chocolate or crispy?

**Comment by JNechaevsky** [comment]
Hi @DartPower, and sorry for late reply.

Multiplayer code was removed from Yaguar, and this project now obsolete - it's now merged into main [Russian Doom](https://github.com/jnechaevsky/russian-doom/) project, and can be simply started as:

* `russian-doom.exe -jaguar` or
* `russian-doom-wide.exe -jaguar`

Multiplayer is working fine in RD, although I'm not sure about the maps - is there MP starts are still on place...
